artifacts_root: artifacts


data_ingestion:
  source:
    type: mysql
    host: 127.0.0.1
    port: 3306
    database: sales
    username: gamesales
    password: ubaid123
    query: "SELECT * FROM videogames;"
  destination:
    type: csv
    path: artifacts/data_ingestion/video_games_sales.csv
    include_column_names: true


data_validation:
  dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/video_games_sales.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  dir: artifacts/data_transformation
  data_dir: artifacts/data_ingestion/video_games_sales.csv